Make libnet dependency illumos-specific
Linux builds (ubuntu 22.04 and 24.04) have been failing locally when
trying to compile `nvpair` with the following error:
```
Checking nvpair v0.5.0 (https://github.com/jmesmon/rust-libzfs?branch=master#ecd5a922)
error[E0308]: mismatched types
   --> /home/treyaspelund.linux/.cargo/git/checkouts/rust-libzfs-262b4bd3f70f4b91/ecd5a92/nvpair/src/lib.rs:530:17
    |
528 |             let v = nvpair_sys::nvlist_pack(
    |                     ----------------------- arguments to this function are incorrect
529 |                 self.as_ptr() as *mut _,
530 |                 &mut ptr,
    |                 ^^^^^^^^ expected `*mut *mut u8`, found `&mut *mut i8`
    |
    = note:    expected raw pointer `*mut *mut u8`
            found mutable reference `&mut *mut i8`
note: function defined here
   --> /home/treyaspelund.linux/.cargo/git/checkouts/rust-libzfs-262b4bd3f70f4b91/ecd5a92/nvpair-sys/src/bindings.rs:331:12
    |
331 |     pub fn nvlist_pack(
    |            ^^^^^^^^^^^

For more information about this error, try `rustc --explain E0308`.
error: could not compile `nvpair` (lib) due to 1 previous error
```

I'm not sure why we don't see the same errors when building on MacOS or
why the linux CI job isn't also failing the same way, but it's worth
fixing just to have local linux builds working so platform-specific
cargo check/clippy/fmt will work properly.

There were 4 main paths nvpair could be pulled in through:

1. bgp → libnet → nvpair (bgp's default feature)
2. bfd → mg-common → libnet → nvpair (mg-common's default feature)
3. bgp → mg-common → libnet → nvpair (both defaults)
4. rdb → mg-common → libnet → nvpair (mg-common's default feature)

Since libnet/nvpair are Illumos-specific, let's make the dependency
reflect that and avoid compilation failures.

Signed-off-by: Trey Aspelund <trey@oxidecomputer.com>