buildomat, bfd, rdb: fix test issues with Db
When executing tests via nextest, some failures were observed with
data store corruption errors.
e.g.
```
2025-11-08T00:21:23.336Z	    thread 'db::test::test_static_routing_ipv6_vlan_id_handling' panicked at rdb/src/db.rs:1334:51:
2025-11-08T00:21:23.336Z	    create db: DataStore(Corruption { at: Some(Inline(130)), bt: () })
2025-11-08T00:21:23.336Z	    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2025-11-08T00:21:23.336Z
2025-11-08T00:21:23.336Z	        FAIL [   0.136s] rdb db::test::test_static_routing_ipv6_basic
```

These started occurring after introducing the get_test_db() method that
consolidates the logic of ensuring uniqueness in test db filepaths.
The initial implementation was not properly accounting for multiple
tests running in different processes. It relied on a global counter
incrementing to provide unique values for the filepath, but each pid
gets its own copy of that counter and thus collisions can still occur.

The following improvements are introduced in this commit:
1. get_test_db uses the PID as an additional value to prevent collisions
2. TestDb wrapper type is added with a Drop impl that ensures old db
   files get cleaned up after a test finishes successfully
3. buildomat jobs now include /tmp/*.db in their output_rules, allowing
   post-mortem inspection of on-disk db state
4. invocation of rdb proptest is fixed (now uses correct mod name)

Signed-off-by: Trey Aspelund <trey@oxidecomputer.com>